name: Update CDN images

on:
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:

jobs:
  process-images:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate image URL mappings
        run: node images.js '${{ secrets.USERNAME }}' '${{ secrets.PASSWORD }}'
        
      # - name: Cleanup processed images
      #   run: node cleanup-images.js
      
      - name: Pull latest changes before commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull --rebase origin main || true
        
      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update CDN images"
          push_options: '--force-with-lease'